# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=400)),
                ('answer', models.CharField(max_length=700)),
                ('counter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('Faq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.Faq')),
            ],
        ),
    ]
